Conditions:
  ShouldSetupProductsCdnCustomDomain: !And
    - !Not
      - !Equals
        - ${env:PRODUCTS_CDN_DOMAIN_NAME, ''}
        - ''
    - !Not
      - !Equals
        - ${env:PRODUCTS_CDN_CERTIFICATE_ARN, ''}
        - ''
    - !Not
      - !Equals
        - ${env:ROUTE53_HOSTED_ZONE_ID, ''}
        - ''


Resources:
  ProductsCDNOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: ${self:service}-${self:provider.stage}-ProductsCDNOAC
        Description: OAC for ProductsBucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  ProductsBucketCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2and3
        Aliases: !If
          - ShouldSetupProductsCdnCustomDomain
          -
            - ${env:PRODUCTS_CDN_DOMAIN_NAME, ''}
          - !Ref AWS::NoValue
        ViewerCertificate: !If
          - ShouldSetupProductsCdnCustomDomain
          -
            AcmCertificateArn: ${env:PRODUCTS_CDN_CERTIFICATE_ARN, ''}
            MinimumProtocolVersion: TLSv1.3_2025
            SslSupportMethod: sni-only
          -
            CloudFrontDefaultCertificate: true
        Origins:
          - Id: S3Origin
            S3OriginConfig: {}
            DomainName: !GetAtt ProductsBucket.RegionalDomainName
            OriginAccessControlId: !Ref ProductsCDNOAC
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # AWS-Managed Cache Policy from CloudFormation doc

  ProductsBucketCDNPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProductsBucket
      PolicyDocument:
        Version: '2008-10-17'
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${ProductsBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${ProductsBucketCDN}'

  ProductsCDNCustomDomainDNSRecord:
    Condition: ShouldSetupProductsCdnCustomDomain
    Type : AWS::Route53::RecordSet
    Properties:
      Name: ${env:PRODUCTS_CDN_DOMAIN_NAME, ''}
      Type: A
      HostedZoneId: ${env:ROUTE53_HOSTED_ZONE_ID, ''}
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # AWS Cloudfront hosted zone id
        DNSName: !GetAtt ProductsBucketCDN.DomainName
