createProduct:
  handler: src/main/functions/product/createProduct.handler
  events:
    - httpApi:
        method: POST
        path: /products
        authorizer:
          name: CognitoAuthorizer
listProducts:
  handler: src/main/functions/product/listProducts.handler
  events:
    - httpApi:
        method: GET
        path: /products
        authorizer:
          name: CognitoAuthorizer
